RETURNGO_API_KEY = "WsIPXwH9w45gaaGrl5BfZ9EeF52MlUqp79G0fIEU"
RETURNGO_API_KEY_BOUNTY = "G0dxSEprxa5iOAIsK5X6g7fCDdPl09q2882osmWD"

[connections.postgresql]
dialect = "postgresql"
driver = "pg8000"
host = "34.11.167.191"
port = 5432
database = "postgres"
username = "sql01"
password = "Taswell11!"
sslmode = "require"
