RETURNGO_API_KEY="WsIPXwH9w45gaaGrl5BfZ9EeF52MlUqp79G0fIEU"

[connections.postgresql]
dialect = "postgresql+pg8000"
username = "sql01"
password = "Taswell11!"
database = "postgres"
instance_connection_name = "freshdesk-activity-report:us-west1:sql01"