[connections.postgresql]
dialect = "postgresql"
driver = "psycopg2"
host = "34.11.167.191"
port = 5432
database = "postgres"
username = "sql01"
password = "Taswell11!"
sslmode = "require" # Changed from 'Enabled' to 'require' for standard PostgreSQL SSL/TLS behavior

RETURNGO_API_KEY="WsIPXwH9w45gaaGrl5BfZ9EeF52MlUqp79G0fIEU"
